name: C/C++ CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: init
      run: ./bin/init.sh --init --no-update --no-upgrade --lcov --setup --optional
    - name: coverage
      run: ./bin/sonarscanner.sh --coverage
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.0
 