name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: init
      run: ./bin/init.sh --init --no-update --no-upgrade --lcov --setup --optional
    - name: coverage
      run: ./bin/coverageall.sh --all
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.0
 
