name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: init
      run: ./bin/init.sh --init --optional
    - name: coverage
      run: ./bin/coverage.sh --all
