name: C/C++ CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: defaultwriter/c-image-repo:latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
    - uses: actions/checkout@v2
      if: github.event_name == 'pull_request'
      with:
        submodules: true
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}

    - uses: actions/checkout@v2
      if: github.event_name == 'push'
      with:
        submodules: true
        fetch-depth: 0
    - name: init
      run: ./bin/init.sh --init --lcov --setup
    - name: coverage
      run: ./bin/sonarscanner.sh --coverage
    - name: codacy coverage
      run: bash bin/codacy.sh --coverage
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.0
 