name: C/C++ CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: defaultwriter/c-image-repo:latest
    steps:
    - uses: actions/checkout@v4
      # with:
      #   submodules: true
      #   fetch-depth: 0
    - name: config
      run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
    - name: coverage
      run: ./bin/coverageall.sh --all --clean
    - name: sonarscanner
      run: ./bin/sonarscanner.sh --coverage
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: codacy coverage
      run: ./bin/codacy.sh --coverage
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.0
 